Repository mommel/hs-lr-midi-schwurbler, pull requests merged in 2020-10, with the labels that each got.

#37 adds the base for a ble version
  code/SchwurblAir/.gitignore
  code/SchwurblAir/.vscode/extensions.json
  code/SchwurblAir/include/.gitkeep
  code/SchwurblAir/lib/.gitkeep
  code/SchwurblAir/platformio.ini
  code/SchwurblAir/src/ButtonController.cpp
  code/SchwurblAir/src/ButtonController.h
  code/SchwurblAir/src/CommunicationController.cpp
  code/SchwurblAir/src/CommunicationController.h
  code/SchwurblAir/src/HelperFunctions.h
  code/SchwurblAir/src/MidiController.cpp
  code/SchwurblAir/src/MidiController.h
  code/SchwurblAir/src/RotaryController.cpp
  code/SchwurblAir/src/RotaryController.h
  code/SchwurblAir/src/main.cpp
  code/SchwurblAir/src/main.h
  code/SchwurblAir/test/.gitkeep
  code/Schwurlber.code-workspace
Labels: merge

#39 moved amount values to buildtime constants
  code/SchwurblAir/platformio.ini
  code/SchwurblAir/src/ButtonController.cpp
  code/SchwurblAir/src/ButtonController.h
  code/SchwurblAir/src/HelperFunctions.h
  code/SchwurblAir/src/MidiController.cpp
  code/SchwurblAir/src/RotaryController.cpp
  code/SchwurblAir/src/RotaryController.h
  code/SchwurblAir/src/main.cpp
  code/SchwurblAir/src/main.h
Labels: merge

#40 fixes codacy findings
  code/SchwurblAir/src/ButtonController.cpp
  code/SchwurblAir/src/MidiController.cpp
  code/SchwurblAir/src/RotaryController.cpp
  code/SchwurblAir/src/main.cpp
Labels: merge

#41 Initial Setup for Schwurbler 360
  .gitignore
  3d-prints/Schwurbler360/.gitkeep
  bom/Schwurbler360/.gitkeep
  circuit-diagram/Schwurbler360/.gitkeep
  code/SchwurblAir/test/test_desktop/test_empty.cpp
  code/Schwurbler360/Schwurbler360/.gitignore
  code/Schwurbler360/Schwurbler360/.vscode/extensions.json
  code/Schwurbler360/Schwurbler360/include/.gitkeep
  code/Schwurbler360/Schwurbler360/lib/.gitkeep
  code/Schwurbler360/Schwurbler360/platformio.ini
  code/Schwurbler360/Schwurbler360/src/main.cpp
  code/Schwurbler360/Schwurbler360/src/main.h
  code/Schwurbler360/Schwurbler360/src/name.c
  code/Schwurbler360/Schwurbler360/test/.gitkeep
  code/Schwurbler360/Schwurbler360/test/test_main.cpp
  kicad/Schwurbler360/.gitkeep
  midi2lr-profiles/Schwurbler360/.gitkeep
  pcb/Schwurbler360/.gitkeep
  prototyping/Schwurbler360/.gitkeep
  quickstartguide/Schwurbler360/.gitkeep
Labels: hacktoberfest-accepted, merge

#46 Add a Codacy badge to README.md
  README.md
Labels: merge

#47 Test automerge rules working as intended
  .github/auto-merge.yml
Labels: merge

#48 Testing last changes on automege
  code/Schwurbler360/README.md
Labels: merge

#49 S360 special automerge for this devbranch
  .github/auto-merge.yml
Labels: merge

#53 adds workplace for vscode for all 3 projects adds editors config to g…
  .gitignore
  code/. editorconfig
  code/Schwurbler.code-workspace
Labels: hacktoberfest-accepted

#61 Create makefile for wiki
  wiki/Makefile
Labels: hacktoberfest-accepted
